In [2]:
# NUMPY ARRAYS

In [3]:
import numpy as np
a = np.array([1,2,3,4])

In [7]:
np.empty(2)

array([ 3.69964218e-236, -3.87960536e+129])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.linspace(0,10 , num =5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.sort([1,4,2,3,6,5])

array([1, 2, 3, 4, 5, 6])

In [11]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
# Creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# Creating 3D array
c = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

Initial PlaceHolder in Numpy Array

In [ ]:
np.zeros(5,dtype="int64")

array([0, 0, 0, 0, 0], dtype=int64)

In [16]:
np.ones((5,4),dtype="int32")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [18]:
np.full((5,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [20]:
# Creating Identity matrix
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
# Create a Numpy array with random values
np.random.random((5,3))

array([[0.38417546, 0.21698175, 0.51133097],
       [0.46272494, 0.73369345, 0.92660321],
       [0.64334173, 0.70619217, 0.82270242],
       [0.01023682, 0.18205689, 0.62394542],
       [0.48394867, 0.43163741, 0.50949512]])

In [23]:
# Create a Numpy array with random values in a range
np.random.randint(0,10,(3,3))

array([[6, 4, 3],
       [5, 6, 6],
       [3, 4, 4]])

In [25]:
# Array with evenly spaced numbers
np.linspace(0,10,5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# array of evenly spaced numbers over a specified space
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
# convert list to numpy array
list = [1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

In [29]:
# convert tuple to numpy array
tuple = (1,2,3,4)
np.array(tuple)


array([1, 2, 3, 4])

Analysing a Numpy array

In [31]:
c = np.random.randint(0,10,(5,5))
c

array([[3, 1, 0, 1, 0],
       [1, 2, 5, 3, 4],
       [3, 7, 8, 4, 5],
       [2, 4, 1, 5, 8],
       [1, 8, 6, 9, 0]])

In [32]:
# Shape of array
c.shape

(5, 5)

In [33]:
# Dimension of array
c.ndim

2

In [34]:
# Size of array
c.size


25

In [35]:
# Data type of array
c.dtype

dtype('int32')

Mathematical operations on a np array

In [37]:
a = np.random.randint(0,10,(5,5))
b = np.random.randint(10,20,(5,5))

In [39]:
print(a)
print(b)

[[9 7 7 5 2]
 [9 1 5 7 4]
 [7 8 3 9 9]
 [9 4 9 9 7]
 [2 6 1 8 1]]
[[12 17 15 16 15]
 [12 19 17 19 10]
 [15 15 17 13 15]
 [13 16 14 15 13]
 [12 13 19 12 17]]


In [41]:
# Addition of two arrays
print(a+b)

[[21 24 22 21 17]
 [21 20 22 26 14]
 [22 23 20 22 24]
 [22 20 23 24 20]
 [14 19 20 20 18]]


In [42]:
# Addition of two arrays
print(np.add(a,b))

[[21 24 22 21 17]
 [21 20 22 26 14]
 [22 23 20 22 24]
 [22 20 23 24 20]
 [14 19 20 20 18]]


In [43]:
# Subtraction of two arrays
print(a-b)

# Subtraction of two arrays
print(np.subtract(a,b))

[[ -3 -10  -8 -11 -13]
 [ -3 -18 -12 -12  -6]
 [ -8  -7 -14  -4  -6]
 [ -4 -12  -5  -6  -6]
 [-10  -7 -18  -4 -16]]
[[ -3 -10  -8 -11 -13]
 [ -3 -18 -12 -12  -6]
 [ -8  -7 -14  -4  -6]
 [ -4 -12  -5  -6  -6]
 [-10  -7 -18  -4 -16]]


In [44]:
# Multiplication of two arrays
print(a*b)

# Multiplication of two arrays
print(np.multiply(a,b))

[[108 119 105  80  30]
 [108  19  85 133  40]
 [105 120  51 117 135]
 [117  64 126 135  91]
 [ 24  78  19  96  17]]
[[108 119 105  80  30]
 [108  19  85 133  40]
 [105 120  51 117 135]
 [117  64 126 135  91]
 [ 24  78  19  96  17]]


In [45]:
# Division of two arrays
print(a/b)

# Division of two arrays
print(np.divide(a,b))


[[0.75       0.41176471 0.46666667 0.3125     0.13333333]
 [0.75       0.05263158 0.29411765 0.36842105 0.4       ]
 [0.46666667 0.53333333 0.17647059 0.69230769 0.6       ]
 [0.69230769 0.25       0.64285714 0.6        0.53846154]
 [0.16666667 0.46153846 0.05263158 0.66666667 0.05882353]]
[[0.75       0.41176471 0.46666667 0.3125     0.13333333]
 [0.75       0.05263158 0.29411765 0.36842105 0.4       ]
 [0.46666667 0.53333333 0.17647059 0.69230769 0.6       ]
 [0.69230769 0.25       0.64285714 0.6        0.53846154]
 [0.16666667 0.46153846 0.05263158 0.66666667 0.05882353]]


Array Manipulation

In [48]:
array = np.random.randint(0,10,(5,5))
array


array([[8, 3, 8, 7, 3],
       [8, 9, 5, 8, 6],
       [5, 6, 0, 4, 7],
       [1, 1, 5, 7, 7],
       [2, 5, 1, 9, 2]])

In [49]:
# transpose of array
array.T

array([[8, 8, 5, 1, 2],
       [3, 9, 6, 1, 5],
       [8, 5, 0, 5, 1],
       [7, 8, 4, 7, 9],
       [3, 6, 7, 7, 2]])

In [50]:
# transpose of array
array.transpose()

array([[8, 8, 5, 1, 2],
       [3, 9, 6, 1, 5],
       [8, 5, 0, 5, 1],
       [7, 8, 4, 7, 9],
       [3, 6, 7, 7, 2]])

In [51]:
# reshape of array
array.reshape(25,1)

array([[8],
       [3],
       [8],
       [7],
       [3],
       [8],
       [9],
       [5],
       [8],
       [6],
       [5],
       [6],
       [0],
       [4],
       [7],
       [1],
       [1],
       [5],
       [7],
       [7],
       [2],
       [5],
       [1],
       [9],
       [2]])